### PR TITLE
[VUFIND-1525] Use Marc4j normalizers; streamline/update build process.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR updates some outdated elements of the browse handler build process:

- It uses marc4j call number libraries instead of deprecated solrmarc libraries.
- It eliminates the need to bundle MarcImporter.jar binaries into the project by pulling everything from VuFind.

TODO:
- [x] Test everything
- [x] Close [VUFIND-1525](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1525) when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@mtrojan-ub, not sure if you're at all invested in AlphaBrowse, but since you've had good feedback on other Java-related PRs, I thought you might be able to help review this one.

**Review by todolson — APPROVED** [review]
I believe this looks good.

**Comment by todolson** [comment]
An upcoming task will need to be removing the `org.solrmarc.callnum` package from SolrMarc.

**Review by mtrojan-ub — APPROVED** [review]
I can't really say much about this one, but it looks like a small + plausible change, so i guess there shouldn't be any negative side effects.

**Comment by demiankatz** [comment]
Thanks, @todolson and @mtrojan-ub! I've opened https://github.com/solrmarc/solrmarc/issues/98 to track the cleanup of the package in SolrMarc itself.

**Pull request merged**
