### PR TITLE
Get browse handlers to build with Solr 9.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Test everything
- [x] Do not merge until we are also ready to merge https://github.com/vufind-org/vufind/pull/2580

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm working on getting this to build for Solr 9. At this point, it's compiling, but I haven't yet been able to set up a fully functional test environment to try it out (see [vufind#2580](https://github.com/vufind-org/vufind/pull/2580) for progress reports on that front). I also notice that the GitHub Actions test build is failing because it's pulling the VuFind dev branch, which currently has Solr 8, and these changes are backward-incompatible. We'll have to coordinate our merges accordingly.

**Comment by demiankatz** [comment]
I've made some progress, but things aren't working. When I spin up the test environment from https://github.com/vufind-org/vufind/pull/2580 with the .jars from this PR included, the indexing step appears to work, but the browse handler fails. On the first attempt, I get:

java.lang.RuntimeException: java.sql.SQLException: Error opening connection

...and on subsequent attempts, I get:

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[],&#8203; int)'

Clearly, something is going wrong with SQLite, but I'm not sure how best to obtain a more detailed trace to understand exactly what is failing and where. Any advice, @todolson or @marktriggs?

**Comment by marktriggs** [comment]
@demiankatz It's a bit of a shot in the dark, but one place I've seen this kind of error is when the OS is configured to block executing code from /tmp (i.e. the filesystem is mounted with `noexec`).  Is that a possibility?

**Comment by demiankatz** [comment]
Thanks, @marktriggs; unfortunately, I don't think that's the case -- at least, I was just now able to create a shell script in /tmp, give it executable permission, and run it.

I guess for the moment, my question is really how best to debug this code. For example, is there something I can easily do to dump more detailed information into the Solr log through the code, or to increase verbosity of the existing messages through Solr configuration? I've never done any deep work with handler development, so I'm just not overly familiar with the available tooling. Obviously, I can do research if nobody else has a quick answer, but just checking first to see if there's something easy/obvious.

**Comment by marktriggs** [comment]
@demiankatz Probably no really easy options :)  Since the error seems to be coming from SQLite's initialization, I don't think debugging at the level of the Solr handler will yield much.

This error:

```java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[],​ int)'```

Suggests that the SQLite jar is being found and loaded, but then failing to load the `libsqlitejdbc.so` native library that implements SQLite.  When sqlite-jdbc is loaded, it unpacks itself into `/tmp` and then attempts to `dlopen` a platform-specific libsqlitejdbc.so, and that's the part that seems to be failing.

One possibly useful trick is to use JRuby to test whether SQLite can be made to work on its own.  You could try something like:

```
curl -O https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.3.8.0/jruby-complete-9.3.8.0.jar

# Maybe check my paths here :)
java -cp jruby-complete-9.3.8.0.jar:/usr/local/vufind/solr/vufind/jars/sqlite-jdbc-3.39.3.0.jar org.jruby.Main -e 'puts java.sql.DriverManager.getConnection("jdbc:sqlite:/tmp/test.db")'
```

If that prints:

`org.sqlite.jdbc4.JDBC4Connection@1c6a0103`

then SQLite loaded successfully and the mystery continues.  But if it fails, maybe posting the output of:

```
strace -s 1000 -f java -cp jruby-complete-9.3.8.0.jar:/usr/local/vufind/solr/vufind/jars/sqlite-jdbc-3.39.3.0.jar org.jruby.Main -e 'puts java.sql.DriverManager.getConnection("jdbc:sqlite:/tmp/test.db")' 2>strace.log
```

would give some clues about what's happening...

**Comment by demiankatz** [comment]
Thanks, @marktriggs. Unfortunately, I think the mystery continues...

I built a browse index using the indexer compiled from this pull request. I then confirmed that the browse handler compiled from this pull request fails when trying to search that index. I copied one of the databases (title browse, though I don't think it matters which one) to /tmp/test.db and ran your proposed JRuby-based test procedure, and it succeeded with `org.sqlite.jdbc4.JDBC4Connection@d25e878`. So I remain unsure what is going wrong or why, especially given that this works fine with the Solr 8 build using the same JDBC jar, and none of the changes here are directly related to database access.

I'd still love to figure out a way to see a full backtrace, in case the database failures are somehow showing up as a side effect of some other issue.

It seems strange to me that I only get "Error opening connection" once, followed by the unsatisfied link errors. Is it possible that there's a bug in the code where, if a connection fails, instead of retrying on subsequent requests, it instead attempts to access a null database connection, or something like that? I'm wondering if there's some weird interaction between the concurrent hash map and failed database connections. But of course, if that's a problem, it's only a secondary one, and the more pressing question is why the initial connection is going wrong!

**Comment by marktriggs** [comment]
@demiankatz Ah well, got to love a good mystery.

I was able to replicate the issue locally too.  I think Solr 9 is running with JVM-level security management enabled, and that's blocking SQLite from loading its shared library.  Running Solr from the console (with the `-f` option) I got this error:

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary./tmp/sqlite-3.39.3.0-8e31a7a9-cb6e-49dd-8c82-11d6d9e8efc2-libsqlitejdbc.so")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:416) ~[?:?]
        at java.lang.SecurityManager.checkLink(SecurityManager.java:703) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:748) ~[?:?]
        at java.lang.System.load(System.java:1953) ~[?:?]
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280) ~[?:?]
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237) ~[?:?]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350) ~[?:?]
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68) ~[?:?]
        at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[?:?]
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278) ~[?:?]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) ~[?:?]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[?:?]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[?:?]
        at org.sqlite.JDBC.createConnection(JDBC.java:104) ~[?:?]
        at org.sqlite.JDBC.connect(JDBC.java:77) ~[?:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:252) ~[java.sql:?]
        at org.vufind.solr.handler.HeadingsDB.openDB(HeadingsDB.java:59) ~[?:?]
        at org.vufind.solr.handler.HeadingsDB.reopenIfUpdated(HeadingsDB.java:103) ~[?:?]
        ... 50 more
```

and with a bit of Google snooping, I found that if I turn off the security manager by setting:

`SOLR_SECURITY_MANAGER_ENABLED=false`

before starting up Solr, then I'm OK.

That does seem to be new in Solr 9.  From: https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html

> Solr now runs with the Java security manager enabled by default. Hadoop users may need to disable this.

**Comment by demiankatz** [comment]
Aha, very interesting! Thanks, @marktriggs! One simple solution to this problem can be to modify VuFind's Solr startup scripts so that they default SOLR_SECURITY_MANAGER_ENABLED to false unless overridden by an existing environment variable. That should allow this to work without eliminating the ability to use the security manager (which may be desirable in situations where alphabrowse is not required).

Of course, an even better solution would be to figure out a way to allow the handler to work correctly with the security manager enabled... but I am unfamiliar with how any of this works, so I'm not sure if that's feasible, or how complicated that is. I welcome input if anybody knows more about it, but at least I have a path forward to continue testing everything.

Thanks again!

**Comment by demiankatz** [comment]
Update: as predicted, defaulting SOLR_SECURITY_MANAGER_ENABLED to false in solr.sh fixes everything; VuFind's full test suite is now passing with Solr 9 and browse handler jars built from this PR! Since this PR is backward-breaking, I won't merge it until we also merge https://github.com/vufind-org/vufind/pull/2580.

**Comment by demiankatz** [comment]
This code is working for me and all VuFind tests are passing, but the upgrade to Solr 9 seems to have broken the test suite here. In order to avoid muddling things, I'm going to merge this even though it will break the build, and I will open a separate PR to work on fixing the test suite.

**Pull request merged**
